# NUMPY

In [4]:
import numpy as np
import pandas as pd

# array 정의

In [5]:
data1 = [1,2,3,4,5]
data2 = [1,2,3,3.5,4]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [6]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('int64')

In [17]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4.shape

(4, 3)

# zeros, ones, arrange함수

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,5)) #row 3 x column 5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
one = np.ones((2,10))
one

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [25]:
np.eye(3) #대각선

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.random((3,2))

array([[0.56885664, 0.6883371 ],
       [0.4461156 , 0.48191535],
       [0.57547978, 0.84247559]])

In [12]:
one.reshape(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# NaN 확인

In [14]:
np.isnan(arr1) # False - not null 

array([False, False, False, False, False])

# Stat 함수

In [19]:
np.sum(arr4)

78

In [20]:
np.sum(arr4, axis=1)

array([ 6, 15, 24, 33])

In [22]:
np.sum(arr4, axis=0)

array([22, 26, 30])

In [28]:
np.mean(arr4)

6.5

In [24]:
np.std(arr4)

3.452052529534663

In [26]:
np.sort(arr4) #오름차손

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
np.sort(arr4)[::-1] #내림차순

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

# 크기

In [20]:
matrix = np.array([[1,2],[1,2],[1,2]])

In [21]:
matrix.ndim 

2

In [22]:
matrix.shape

(3, 2)