# Splitting Data 
 * for supervised learning
 - 기계를 훈련시키기 위해서 데이터를 총 4개로 나눔 -> 훈련 데이터 (문제지, 정답), 테스트 데이터 (시험지, 정답)

1. ZIP

In [1]:
x, y = zip(['a',1],['b',2],['c',3])
print(x,y)

('a', 'b', 'c') (1, 2, 3)


In [10]:
sequence = [['a',1],['b',2],['c',3]]
x, y=zip(*sequence)
print(x,y)
print(list(zip(x,y)))

('a', 'b', 'c') (1, 2, 3)
[('a', 1), ('b', 2), ('c', 3)]


2. PANDA

In [14]:
import pandas as pd
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

In [17]:
df = pd.DataFrame(values, columns = columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [22]:
X = df['메일 본문']
y = df['스팸 메일 유무']
X.to_list()
y.to_list()

[1, 0, 0, 1]

In [32]:
import numpy as np
np_array = np.arange(0,16).reshape((4,4))
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
X=np_array[:,:3]
y=np_array[:,3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# 테스트 데이터 분리하기

In [43]:
#USING SKLEARN
from sklearn.model_selection import train_test_split #사이킷런
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

In [50]:
X, y = np.arange(10).reshape((5,2)),range(5)
print(X, '\n', y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 
 range(0, 5)


In [51]:
print(X_train)
print(y_train)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0, 1, 2, 3]


In [52]:
print(X_test) #20% 가 TEST
print(y_test)

[[8 9]]
[4]


In [59]:
#USING 수동 분리

X, y = np.arange(0,24).reshape((12,2)),range(12) # range 가 y 임
num_of_train = int(len(X)*0.8) # train 80%, test 20%

In [60]:
X_test = X[num_of_train:]
y_test = y[num_of_train:]
X_train = X[:num_of_train]
y_train = y[:num_of_train]