##### Integer Encoding
 - Integer Encoding -> Padding -> One-Hot Encoding
 단어집합(vocabulary)를 만들기 위해서는 문자를 숫자로 바꾸는 integer encoding을 진행함
 따라서, 예) 1~5000 까지 단어들에게 인덱스를 부여함. 
 그리고, 정수 인덱스를 부여하여 구체적인 벡터로 바꾸는것이 원-핫 (ONE HOT ENCODING)이라고 생각하면 됨. 
 
 
- Raw Text에서 tokenize해야함 (split into sentences, or words first)
- stopword 제외 & length 2 보다 적은거 제외
- dictionary로 만들어서 count 함
- 정수 0부터 빈도수에 따라 mapping함 -> vocab 만듬
- vocab을 만들어서, vector에 적용함
- Matrix 만듬 (특정 word에 따라서 matrix을 만듬) -> One Hot Encoding
 
INTEGER ENCODING
* 각 단어를 숫자에 mapping 시킴 
* 보통 단어 빈도수를 기준으로 정렬하여 부여함 
* 빈도수 순으로 낮은 숫자 정수를 부여하여 (Vocabulary)를 만들으면 좋음 

## 1) 
tokenize -> stopword 제외&소문자&길이 2이상만넣음 -> dictionary로 만들음

In [2]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [3]:
raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [7]:
tokenizer = word_tokenize(raw_text)
print(tokenizer)

['A', 'barber', 'is', 'a', 'person', '.', 'a', 'barber', 'is', 'good', 'person', '.', 'a', 'barber', 'is', 'huge', 'person', '.', 'he', 'Knew', 'A', 'Secret', '!', 'The', 'Secret', 'He', 'Kept', 'is', 'huge', 'secret', '.', 'Huge', 'secret', '.', 'His', 'barber', 'kept', 'his', 'word', '.', 'a', 'barber', 'kept', 'his', 'word', '.', 'His', 'barber', 'kept', 'his', 'secret', '.', 'But', 'keeping', 'and', 'keeping', 'such', 'a', 'huge', 'secret', 'to', 'himself', 'was', 'driving', 'the', 'barber', 'crazy', '.', 'the', 'barber', 'went', 'up', 'a', 'huge', 'mountain', '.']


In [222]:
stop_words = set(stopwords.words('english'))

In [50]:
from collections import Counter
lst = list()
preprocessed = list()
for i in tokenizer:
    word = i.lower()
    if len(word) <= 2:
        continue
    if word in stop_words:
        continue
    lst.append(word)
    
print(lst)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [44]:
#심지어 sort도 해줌
my_counter = (Counter(lst)) 
#delete vocab_size less than 5
print(my_counter)
vocab=my_counter.most_common(5)
vocab

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [43]:
# Indexing 부여
i=0
vocab_dict = {}
for word, frequency in vocab:
    i = i + 1
    vocab_dict[word] = i
    
print(vocab_dict)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


## 2 NLTK 의 FreqDist 사용

In [45]:
from nltk import FreqDist
import numpy as np

In [52]:
sentences = sent_tokenize(raw_text)

In [71]:
#책에서는 sentence로 나눔
preprocessed = []
for sentence in sentences:
    tok = word_tokenize(sentence)
    result = []
    for word in tok:
        word = word.lower()
        if len(word)>2:
            if word not in stop_words:
                result.append(word)
    preprocessed.append(result)
            
print(preprocessed)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [72]:
vocab = FreqDist(np.hstack(preprocessed))
print(vocab)
vocab_1=vocab.most_common(5)
vocab_1

<FreqDist with 13 samples and 36 outcomes>


[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [88]:
#1
word_index = {}
for a,b in enumerate(vocab_1):
    word_index[b[0]] = a+1
print(word_index)
#2
word_index2 = {word[0] : index+1 for index,word in enumerate(vocab_1)}
print(word_index2)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [89]:
# Out - Of - Vocabulary (OOV)
word_index2['OOV'] = len(word_index2) + 1
word_index2

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}

# 3 Use Keras

In [91]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [122]:
#sentence 로 나눠서 각 list에 들어가있는 "preprocessed 사용 "
print(preprocessed)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [159]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed) 
#너무 쉬움. dictionary에 다 넣어줌, 빈도수를 이용해서 indexing까지 해줌
print(tokenizer.word_index,"\n") # index 부여
print(tokenizer.word_counts) # word count

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13} 

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [160]:
print(tokenizer.texts_to_sequences(preprocessed))
encode = tokenizer.texts_to_sequences(preprocessed)
encoded = tokenizer.texts_to_sequences(preprocessed)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [125]:
tokenizer = Tokenizer(num_words = 6) #상위 5개
tokenizer.fit_on_texts(preprocessed)
print(tokenizer.texts_to_sequences(preprocessed))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [126]:
#OOV 설정
tokenizer = Tokenizer(num_words = 7, oov_token="OOV")
tokenizer.fit_on_texts(preprocessed)
print(tokenizer.texts_to_sequences(preprocessed))

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


In [127]:
print(tokenizer.word_index['OOV']) #OOV 는 1로 설정됨

1


# Padding - 길이 동일하게 맞춰주기

In [154]:
#Using NUMPY
numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
# NUMPY - find max lwength, and then array until the max. ength

i = []
for item in encode:
    i.append(len(item))
max_len = max(i) 

In [155]:
# max 길이로 맞출거임, 7보다 작은경우에는 0으로 대체할거임

for sentence in encode:
    while len(sentence) < max_len:
        sentence.append(0)
padded = np.array(encode)
padded #zero-padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [156]:
#Using KERAS 
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [162]:
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [164]:
padded = pad_sequences(encoded)
padded #저절로 padding

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [169]:
padded_1= pad_sequences(encoded, padding = 'post')
padded_1 #저절로 padding

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [172]:
padded_2= pad_sequences(encoded, padding = 'post', value = 0, truncating='post', maxlen = 5 )
padded_2 #저절로 padding

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]], dtype=int32)

# One-Hot Encoding

In [173]:
from konlpy.tag import Okt

In [175]:
okt = Okt()
tokens = okt.morphs('나는 자연어 처리를 배운다')
print(tokens)

['나', '는', '자연어', '처리', '를', '배운다']


In [183]:
word_to_index = {word : index for index, word in enumerate(tokens)}
word_to_index

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}

In [184]:
def one_hot_encoding(word, word_to_index):
  one_hot_vector = [0]*(len(word_to_index))
  index = word_to_index[word]
  one_hot_vector[index] = 1
  return one_hot_vector

In [185]:
one_hot_encoding('자연어', word_to_index) # 원-핫 벡터

[0, 0, 1, 0, 0, 0]

In [186]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [218]:
text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

In [219]:
print(tokenizer.word_index)
print(tokenizer.word_counts)

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}
OrderedDict([('나랑', 1), ('점심', 2), ('먹으러', 1), ('갈래', 3), ('메뉴는', 1), ('햄버거', 2), ('최고야', 1)])


In [220]:
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
encoded

[2, 5, 1, 6, 3, 7]

In [216]:
one_hot = to_categorical(encoded) #matrix만들기/ 각 index에 대한 원-핫 백터
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [228]:
#text을 가지고 해보자
print(text)
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
coding = tokenizer.texts_to_sequences([text])[0]
coding

나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야


[4, 2, 5, 1, 2, 6, 3, 1, 1, 3, 7]

In [231]:
print(len(coding))
one_hot_2 = to_categorical(coding)
one_hot_2

11


array([[0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)